### ISSUE TITLE
Firefox Quantum - The script interact with the Tampermonkey dropdown menu and create an huge space on top list

### ISSUE THREAD

**Issue by decembre** [eight04/linkify-plus-plus-core#13]
That's strange and only on my Test profile of Firefox Quantum (normally i use Waterfox).

This huge space on top appear only when your script is enable.... and only on certain sites !.
Screenshot:
![LINKIFY PLUS - PB MENU - GIF 01-05-2021 17-25-20](https://user-images.githubusercontent.com/868778/116787333-b354c380-aaa3-11eb-971b-91054a47ef3c.gif)

My test:
That's occur on Greasyfork, YouTube sites by example...
On others sites no problem.
I try to disable others scripts and many addons, but that's the same.
Reload the browser don't change anything too.
When i use an other Quantum profile no problem.

i uncheck all options in your script too.
There are no particular settings added and not for these domains where the huge space appear.
I don't understand this effect.
An idea ?

**Comment by eight04** [comment]
You have to report this issue to Tampermonkey. The UI is controlled by the script manager instead of the script.

**Comment by decembre** [comment]
ok....
